# from https://cs231n.github.io/python-numpy-tutorial/

# -*- coding: utf-8 -*-
"""Copy of colab-tutorial.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GWMh9xLcLAsdraiBvZdaBuejESgUYAsE

#CS231n Python Tutorial With Google Colab

This tutorial was originally written by [Justin Johnson](https://web.eecs.umich.edu/~justincj/) for cs231n. It was adapted as a Jupyter notebook for cs228 by [Volodymyr Kuleshov](http://web.stanford.edu/~kuleshov/) and [Isaac Caswell](https://symsys.stanford.edu/viewing/symsysaffiliate/21335).

This version has been adapted for Colab by Kevin Zakka for the Spring 2020 edition of [cs231n](https://cs231n.github.io/). It runs Python3 by default.

##Introduction

We will use the Python programming language for all assignments in this course. Python is a great general-purpose programming language on its own, but with the help of a few popular libraries (`numpy`, `scipy`, `matplotlib`) it becomes a powerful environment for scientific computing.

We expect that many of you will have some experience with Python and numpy; for the rest of you, this section will serve as a quick crash course both on the Python programming language and on the use of Python for scientific computing. We’ll also introduce notebooks, which are a very convenient way of tinkering with Python code. Some of you may have previous knowledge in a different language, in which case we also recommend referencing: 

- [NumPy for Matlab users](https://numpy.org/doc/stable/user/numpy-for-matlab-users.html)

- [Python for R users](http://www.data-analysis-in-python.org/python_for_r.html)

- [Python for SAS users](https://nbviewer.jupyter.org/github/RandyBetancourt/PythonForSASUsers/tree/master/)

In this tutorial, we will cover:

- Basics of Python: 
    + Basic data types
    + Containers: Lists, Dictionaries, Sets, Tuples
    + Functions
    + Classes

- Numpy: Arrays, Array indexing, Datatypes, Array math, Broadcasting

- Matplotlib: Plotting, Subplots, Images

## A Brief Note on Python Versions

As of Janurary 1, 2020, Python has [officially dropped support](https://www.python.org/doc/sunset-python-2/) for `python2`. We'll be using Python 3.7 for this iteration of the course. You can check your Python version at the command line by running `python --version`. In Colab, we can enforce the Python version by clicking `Runtime -> Change Runtime Type` and selecting `python3`. Note that as of April 2020, Colab uses Python 3.6.9 which should run everything without any errors.
"""

!python --version

"""##Basics of Python

Python is a high-level, dynamically typed multiparadigm programming language. Python code is often said to be almost like pseudocode, since it allows you to express very powerful ideas in very few lines of code while being very readable. As an example, here is an implementation of the classic quicksort algorithm in Python:
"""

def quicksort(arr):
    if len(arr) <= 1:
        return arr
    pivot = arr[len(arr) // 2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]
    return quicksort(left) + middle + quicksort(right)

print(quicksort([3, 6, 8, 10, 1, 2,1 ]))

"""###Basic data types

Like most languages, Python has a number of basic types including integers, floats, booleans, and strings. These data types behave in ways that are familiar from other programming languages.

**Numbers:** Integers and floats work as you would expect from other languages:
"""

x = 3
print(x)

print(type(x))

"""Addition"""

print(x + 1)

x += 1
print(x)

"""Subtraction"""

print(x - 1)

"""Multiplication"""

print(x * 2)

x *= 2
print(x)

""" Exponentiation"""

print(x ** 2)

"""Addition, Multiplication, and Exponentiation"""

y = 2.5
print(type(y))

print(y, y + 1, y * 2, y ** 2)

"""Note that unlike many languages, Python does not have unary increment (`x++`) or decrement (`x--`) operators.

Python also has built-in types for long integers and complex numbers; you can find all of the details in the [documentation](https://docs.python.org/3.7/library/stdtypes.html#numeric-types-int-float-long-complex).

**Booleans:** Python implements all of the usual operators for Boolean logic, but uses English words rather than symbols (`&&`, `||`, etc.):
"""

t, f = True, False
print(type(t))

"""Now we let's look at the operations:

Logical AND
"""

print(t and f)

"""Logical OR"""

print(t or f)

"""Logical NOT"""

print(not t)

"""Logical XOR"""

print(t != f)

"""**Strings:** Python has great support for strings.

String literals can use single quotes or double quotes; it does not matter
"""

hello = 'hello'
world = "world"
print(hello)

print(len(hello))

"""String concatenation"""

hw = hello + ' ' + world
print(hw)

"""String formatting"""

hw12 = '{} {} {}'.format(hello, world, 12) 
print(hw12)

"""String objects have a bunch of useful methods; for example:

Capitalize a string
"""

s = "hello"
print(s.capitalize())

""" Convert a string to uppercase"""

print(s.upper())

"""Right-justify a string, padding with spaces"""

print(s.rjust(7))

"""Center a string, padding with spaces"""

print(s.center(7))

"""Replace all instances of one substring with another"""

print(s.replace('l', '(ell)'))

"""Strip leading and trailing whitespace"""

print('  world '.strip())

"""You can find a list of all string methods in the [documentation](https://docs.python.org/3.7/library/stdtypes.html#string-methods).

###Containers

Python includes several built-in container types: 

- lists

- dictionaries

- sets

- tuples

####Lists

A list is the Python equivalent of an array, but is resizeable and can contain elements of different types.

Create a list
"""

xs = [3, 1, 2]
print(xs)

print(xs[2])

"""Negative indices count from the end of the list"""

print(xs[-1])

"""Lists can contain elements of different types"""

xs[2] = 'foo'    
print(xs)

"""Add a new element to the end of the list"""

xs.append('bar') 
print(xs)

"""Remove and return the last element of the list"""

x = xs.pop()
print(x, xs)

"""As usual, you can find all the gory details about lists in the [documentation](https://docs.python.org/3.7/tutorial/datastructures.html#more-on-lists).

**Slicing:** In addition to accessing list elements one at a time, Python provides concise syntax to access sublists; this is known as slicing:

Range is a built-in function that creates a list of integers
"""

nums = list(range(5))
print(nums)

"""Get a slice from index 2 to 4 (exclusive)"""

print(nums[2:4])

"""Get a slice from index 2 to the end"""

print(nums[2:])

"""Get a slice from the start to index 2 (exclusive)"""

print(nums[:2])

"""Get a slice of the whole list"""

print(nums[:])

"""Slice indices can be negative"""

print(nums[:-1])

"""Assign a new sublist to a slice"""

nums[2:4] = [8, 9] 
print(nums)

"""**Loops:** You can loop over the elements of a list like this:"""

animals = ['cat', 'dog', 'monkey']
for animal in animals:
    print(animal)

"""If you want access to the index of each element within the body of a loop, use the built-in `enumerate` function:"""

animals = ['cat', 'dog', 'monkey']
for idx, animal in enumerate(animals):
    print('#{}: {}'.format(idx + 1, animal))

"""**List comprehensions:** When programming, frequently we want to transform one type of data into another. As a simple example, consider the following code that computes square numbers:"""

nums = [0, 1, 2, 3, 4]
squares = []
for x in nums:
    squares.append(x ** 2)
print(squares)

"""You can make this code simpler using a **list comprehension**:"""

nums = [0, 1, 2, 3, 4]
squares = [x ** 2 for x in nums]
print(squares)

"""List comprehensions can also contain conditions:"""

nums = [0, 1, 2, 3, 4]
even_squares = [x ** 2 for x in nums if x % 2 == 0]
print(even_squares)

"""####Dictionaries

A dictionary stores (key, value) pairs, similar to a `Map` in Java or an object in Javascript. You can use it like this:

Create a new dictionary with some data
"""

d = {'cat': 'cute', 'dog': 'furry'}

"""Get an entry from a dictionary"""

print(d['cat'])

"""Check if a dictionary has a given key"""

print('cat' in d)

"""Set an entry in a dictionary"""

d['fish'] = 'wet'
print(d['fish'])

"""KeyError: 'monkey' not a key of d"""

print(d['monkey'])

"""Get an element with a default"""

print(d.get('monkey', 'N/A'))

"""Get an element with a default"""

print(d.get('fish', 'N/A'))

"""Remove an element from a dictionary"""

del d['fish']

""""fish" is no longer a key"""

print(d.get('fish', 'N/A'))

"""You can find all you need to know about dictionaries in the [documentation](https://docs.python.org/2/library/stdtypes.html#dict).

**Loops:** It is easy to iterate over the keys in a dictionary:
"""

d = {'person': 2, 'cat': 4, 'spider': 8}
for animal, legs in d.items():
    print('A {} has {} legs'.format(animal, legs))

"""**Dictionary comprehensions:** These are similar to list comprehensions, but allow you to easily construct dictionaries. For example:"""

nums = [0, 1, 2, 3, 4]
even_num_to_square = {x: x ** 2 for x in nums if x % 2 == 0}
print(even_num_to_square)

"""####Sets

A set is an unordered collection of distinct elements. As a simple example, consider the following:
"""

animals = {'cat', 'dog'}

"""Check if an element is in a set"""

print('cat' in animals)

print('fish' in animals)

"""Add an element to a set"""

animals.add('fish')
print('fish' in animals)

"""Number of elements in a set"""

print(len(animals))

"""Adding an element that is already in the set does nothing

"""

animals.add('cat') 
print(len(animals))

"""Remove an element from a set"""

animals.remove('cat') 
print(len(animals))

"""**Loops:** Iterating over a set has the same syntax as iterating over a list; however since sets are unordered, you cannot make assumptions about the order in which you visit the elements of the set:"""

animals = {'cat', 'dog', 'fish'}
for idx, animal in enumerate(animals):
    print('#{}: {}'.format(idx + 1, animal))

"""**Set comprehensions:** Like lists and dictionaries, we can easily construct sets using set comprehensions:"""

from math import sqrt

print({int(sqrt(x)) for x in range(30)})

"""####Tuples

A tuple is an (immutable) ordered list of values. A tuple is in many ways similar to a list; one of the most important differences is that tuples can be used as keys in dictionaries and as elements of sets, while lists cannot. Here is a trivial example:

Create a dictionary with tuple keys
"""

d = {(x, x + 1): x for x in range(10)}

"""Create a tuple"""

t = (5, 6)
print(type(t))

print(d[t])

print(d[(1, 2)])

t[0] = 1

"""###Functions

Python functions are defined using the `def` keyword. For example:
"""

def sign(x):
    if x > 0:
        return 'positive'
    elif x < 0:
        return 'negative'
    else:
        return 'zero'

for x in [-1, 0, 1]:
    print(sign(x))

"""We will often define functions to take optional keyword arguments, like this:"""

def hello(name, loud=False):
    if loud:
        print('HELLO, {}'.format(name.upper()))
    else:
        print('Hello, {}!'.format(name))

hello('Bob')

hello('Fred', loud=True)

"""###Classes

The syntax for defining classes in Python is straightforward:
"""

class Greeter:

    # Constructor
    def __init__(self, name):
        self.name = name  # Create an instance variable

    # Instance method
    def greet(self, loud=False):
        if loud:
          print('HELLO, {}'.format(self.name.upper()))
        else:
          print('Hello, {}!'.format(self.name))

"""Construct an instance of the Greeter class"""

g = Greeter('Fred')

"""Call an instance method"""

g.greet()

"""Call an instance method"""

g.greet(loud=True)

"""##Numpy

Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. If you are already familiar with MATLAB, you might find this [tutorial](http://wiki.scipy.org/NumPy_for_Matlab_Users) useful to get started with Numpy.

To use Numpy, we first need to import the `numpy` package:
"""

import numpy as np

"""###Arrays

A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

Create a rank 1 array
"""

a = np.array([1, 2, 3])
print(type(a))

print(a.shape)

print(a[0], a[1], a[2])

""" Change an element of the array"""

a[0] = 5
print(a)

"""Create a rank 2 array"""

b = np.array([[1, 2, 3], [4, 5, 6]])  
print(b)

print(b.shape)

print(b[0, 0], b[0, 1], b[1, 0])

"""Numpy also provides many functions to create arrays:

Create an array of all zeros
"""

a = np.zeros((2, 2))
print(a)

"""Create an array of all ones"""

b = np.ones((1, 2))   
print(b)

"""Create a constant array"""

c = np.full((2, 2), 7) 
print(c)

"""Create a 2x2 identity matrix"""

d = np.eye(2)
print(d)

"""Create an array filled with random values"""

e = np.random.random((2, 2)) 
print(e)

"""###Array indexing

Numpy offers several ways to index into arrays.

**Slicing:** Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

Create the following rank 2 array with shape (3, 4)

```
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
```
"""

import numpy as np

a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a.shape)

"""Use slicing to pull out the subarray consisting of the first 2 rows and columns 1 and 2; b is the following array of shape (2, 2):

```
[[2 3]
 [6 7]]
```
"""

b = a[:2, 1:3]
print(b)

"""A slice of an array is a view into the same data, so modifying it will modify the original array."""

print(a[0, 1])

"""`b[0, 0]` is the same piece of data as `a[0, 1]`"""

b[0, 0] = 77  
print(a[0, 1])

"""You can also mix integer indexing with slice indexing. However, doing so will yield an array of lower rank than the original array. Note that this is quite different from the way that MATLAB handles array slicing:

Create the following rank 2 array with shape (3, 4)
"""

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

"""Two ways of accessing the data in the middle row of the array.
Mixing integer indexing with slices yields an array of lower rank,
while using only slices yields an array of the same rank as the
original array:

Rank 1 view of the second row of `a`
"""

row_r1 = a[1, :]  
print(row_r1)

print(row_r1.shape)

"""Rank 2 view of the second row of `a`"""

row_r2 = a[1:2, :]
print(row_r2)

print(row_r2.shape)

"""Rank 2 view of the second row of `a`"""

row_r3 = a[[1], :]  
print(row_r3)

print(row_r3.shape)

"""We can make the same distinction when accessing columns of an array:"""

col_r1 = a[:, 1]
print(col_r1)

print(col_r1.shape)

col_r2 = a[:, 1:2]
print(col_r2)

print(col_r2.shape)

"""**Integer array indexing:** When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array. Here is an example:"""

a = np.array([[1,2], [3, 4], [5, 6]])

"""An example of integer array indexing. The returned array will have shape (3,):"""

print(a[[0, 1, 2], [0, 1, 0]])

"""The above example of integer array indexing is equivalent to this:"""

print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

"""When using integer array indexing, you can reuse the same element from the source array:"""

print(a[[0, 0], [1, 1]])

"""Equivalent to the previous integer array indexing example"""

print(np.array([a[0, 1], a[0, 1]]))

"""One useful trick with integer array indexing is selecting or mutating one element from each row of a matrix.

Create a new array from which we will select elements
"""

a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)

"""Create an array of indices"""

b = np.array([0, 2, 0, 1])

"""Select one element from each row of `a` using the indices in `b`"""

print(a[np.arange(4), b])

"""Mutate one element from each row of `a` using the indices in `b`"""

a[np.arange(4), b] += 10
print(a)

"""**Boolean array indexing:** Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. Here is an example:"""

import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

"""Find the elements of a that are bigger than 2; this returns a numpy array of Booleans of the same shape as `a`, where each slot of `bool_idx` tells whether that element of `a` is > 2.

"""

bool_idx = (a > 2)  
print(bool_idx)

"""We use boolean array indexing to construct a rank 1 array consisting of the elements of a corresponding to the `True` values of `bool_idx`"""

print(a[bool_idx])

"""We can do all of the above in a single concise statement:"""

print(a[a > 2])

"""For brevity we have left out a lot of details about numpy array indexing; if you want to know more you should [read the documentation](http://docs.scipy.org/doc/numpy/reference/arrays.indexing.html).

###Datatypes

Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. Here is an example:

Let numpy choose the datatype
"""

x = np.array([1, 2])
print(x.dtype)

"""Let numpy choose the datatype"""

y = np.array([1.0, 2.0])  
print(y.dtype)

"""Force a particular datatype"""

z = np.array([1, 2], dtype=np.int64)  
print(z.dtype)

"""You can read all about numpy datatypes in the [documentation](http://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html).

###Array math

Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:
"""

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

"""Elementwise sum; both produce the array

```
[[ 6.0  8.0]
 [10.0 12.0]]
```
"""

print(x + y)

print(np.add(x, y))

"""Elementwise difference; both produce the array

```
[[-4.0 -4.0]
 [-4.0 -4.0]]
```
"""

print(x - y)

print(np.subtract(x, y))

"""Elementwise product; both produce the array

```
[[ 5.0 12.0]
 [21.0 32.0]]
```
"""

print(x * y)

print(np.multiply(x, y))

"""Elementwise division; both produce the array

```
[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]
```
"""

print(x / y)

print(np.divide(x, y))

"""Elementwise square root; produces the array

```
[[ 1.          1.41421356]
 [ 1.73205081  2.        ]]
```
"""

print(np.sqrt(x))

"""Note that unlike MATLAB, `*` is elementwise multiplication, not matrix multiplication. We instead use the `dot` function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. `dot` is available both as a function in the numpy module and as an instance method of array objects:"""

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

"""Inner product of vectors; both produce 219"""

print(v.dot(w))

print(np.dot(v, w))

"""You can also use the `@` operator which is equivalent to numpy's `dot` operator."""

print(v @ w)

"""Matrix and vector product; both produce the rank 1 array `[29 67]`"""

print(x.dot(v))

print(np.dot(x, v))

print(x @ v)

"""Matrix and matrix product; both produce the rank 2 array

```
[[19 22]
 [43 50]]
```
"""

print(x.dot(y))

print(np.dot(x, y))

print(x @ y)

"""Numpy provides many useful functions for performing computations on arrays; one of the most useful is `sum`:"""

x = np.array([[1, 2],[3, 4]])

"""Compute sum of all elements"""

print(np.sum(x))

"""Compute sum of each column"""

print(np.sum(x, axis=0))

"""Compute sum of each row"""

print(np.sum(x, axis=1))

"""You can find the full list of mathematical functions provided by numpy in the [documentation](http://docs.scipy.org/doc/numpy/reference/routines.math.html).

Apart from computing mathematical functions using arrays, we frequently need to reshape or otherwise manipulate data in arrays. The simplest example of this type of operation is transposing a matrix; to transpose a matrix, simply use the `T` attribute of an array object:
"""

print(x)

print("transpose\n", x.T)

v = np.array([[1, 2, 3]])
print(v)

print("transpose\n", v.T)

"""Numpy provides many more functions for manipulating arrays; you can see the full list in the [documentation](http://docs.scipy.org/doc/numpy/reference/routines.array-manipulation.html).

###Broadcasting

Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

For example, suppose that we want to add a constant vector to each row of a matrix. We could do it like this:

We will add the vector v to each row of the matrix `x`, storing the result in the matrix `y`
"""

x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])

"""Create an empty matrix with the same shape as `x`

"""

y = np.empty_like(x)

"""Add the vector `v` to each row of the matrix `x` with an explicit loop"""

for i in range(4):
    y[i, :] = x[i, :] + v

print(y)

"""This works; however when the matrix `x` is very large, computing an explicit loop in Python could be slow. Note that adding the vector `v` to each row of the matrix `x` is equivalent to forming a matrix `vv` by stacking multiple copies of `v` vertically, then performing elementwise summation of `x` and `vv`. We could implement this approach like this:

Stack 4 copies of `v` on top of each other
"""

vv = np.tile(v, (4, 1))  
print(vv)

"""Add `x` and `vv` elementwise"""

y = x + vv  
print(y)

"""Numpy broadcasting allows us to perform this computation without actually creating multiple copies of `v`. Consider this version, using broadcasting:

We will add the vector `v` to each row of the matrix `x`, storing the result in the matrix `y`
"""

x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])

"""Add `v` to each row of `x` using broadcasting"""

y = x + v
print(y)

"""The line `y = x + v` works even though `x` has shape `(4, 3)` and `v` has shape `(3,)` due to broadcasting; this line works as if `v` actually had shape `(4, 3)`, where each row was a copy of `v`, and the sum was performed elementwise.

Broadcasting two arrays together follows these rules:

1. If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.
2. The two arrays are said to be *compatible* in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.
3. The arrays can be broadcast together if they are compatible in all dimensions.
4. After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.
5. In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension

If this explanation does not make sense, try reading the explanation from the [documentation](http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html) or this [explanation](http://wiki.scipy.org/EricsBroadcastingDoc).

Functions that support broadcasting are known as *universal functions*. You can find the list of all universal functions in the [documentation](http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs).

Here are some applications of broadcasting:

Compute outer product of vectors
"""

v = np.array([1, 2, 3])  # v has shape (3,)
w = np.array([4, 5])     # w has shape (2,)

"""To compute an outer product, we first reshape `v` to be a column vector of shape (3, 1); we can then broadcast it against `w` to yield an output of shape (3, 2), which is the outer product of `v` and `w`:"""

print(np.reshape(v, (3, 1)) * w)

"""Add a vector to each row of a matrix"""

x = np.array([[1,2,3], [4,5,6]])

"""`x` has shape (2, 3) and `v` has shape (3,) so they broadcast to (2, 3), giving the following matrix:"""

print(x + v)

"""Add a vector to each column of a matrix `x` has shape (2, 3) and `w` has shape (2,). If we transpose `x` then it has shape (3, 2) and can be broadcast against `w` to yield a result of shape (3, 2); transposing this result yields the final result of shape (2, 3) which is the matrix `x` with the vector `w` added to each column and gives the following matrix:"""

print((x.T + w).T)

"""Another solution is to reshape `w` to be a row vector of shape (2, 1); we can then broadcast it directly against `x` to produce the same output."""

print(x + np.reshape(w, (2, 1)))

"""Multiply a matrix by a constant: `x` has shape (2, 3). Numpy treats scalars as arrays of shape (); these can be broadcast together to shape (2, 3), producing the following array:"""

print(x * 2)

"""Broadcasting typically makes your code more concise and faster, so you should strive to use it where possible.

##Numpy Documentation
 
This brief overview has touched on many of the important things that you need to know about numpy, but is far from complete. Check out the [numpy reference](http://docs.scipy.org/doc/numpy/reference/) to find out much more about numpy.

#SciPy

Numpy provides a high-performance multidimensional array and basic tools to compute with and manipulate these arrays. [SciPy](http://docs.scipy.org/doc/scipy/reference/) builds on this, and provides a large number of functions that operate on numpy arrays and are useful for different types of scientific and engineering applications.

The best way to get familiar with SciPy is to browse the [documentation](http://docs.scipy.org/doc/scipy/reference/index.html). We will highlight some parts of SciPy that you might find useful for this class.

### Image operations

SciPy provides some basic functions to work with images. For example, it has functions to read images from disk into numpy arrays, to write numpy arrays to disk as images, and to resize images. Here is a simple example that showcases these functions:
"""

from scipy.misc import imread, imsave, imresize

"""Read an JPEG image into a numpy array"""

img = imread('assets/cat.jpg')
print(img.dtype, img.shape)  # Prints "uint8 (400, 248, 3)"

"""We can tint the image by scaling each of the color channels by a different scalar constant. The image has shape (400, 248, 3); we multiply it by the array [1, 0.95, 0.9] of shape (3,); numpy broadcasting means that this leaves the red channel unchanged, and multiplies the green and blue channels by 0.95 and 0.9 respectively."""

img_tinted = img * [1, 0.95, 0.9]

"""Resize the tinted image to be 300 by 300 pixels."""

img_tinted = imresize(img_tinted, (300, 300))

"""Write the tinted image back to disk"""

imsave('assets/cat_tinted.jpg', img_tinted)

"""## MATLAB files

The functions `scipy.io.loadmat` and `scipy.io.savemat` allow you to read and write MATLAB files. You can read about them in the [documentation](http://docs.scipy.org/doc/scipy/reference/io.html).

### Distance between points

SciPy defines some useful functions for computing distances between sets of points.

The function `scipy.spatial.distance.pdist` computes the distance between all pairs of points in a given set:
"""

import numpy as np
from scipy.spatial.distance import pdist, squareform

"""Create the following array where each row is a point in 2D space:
```
[[0 1]
 [1 0]
 [2 0]]
```
"""

x = np.array([[0, 1], [1, 0], [2, 0]])
print(x)

"""Compute the Euclidean distance between all rows of `x`. `d[i, j]` is the Euclidean distance between `x[i, :]` and `x[j, :]`, and `d` is the following array:

```
[[ 0.          1.41421356  2.23606798]
 [ 1.41421356  0.          1.        ]
 [ 2.23606798  1.          0.        ]]
```
"""

d = squareform(pdist(x, 'euclidean'))
print(d)

"""You can read all the details about this function in the [documentation](http://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.distance.pdist.html).

A similar function, `scipy.spatial.distance.cdist`, computes the distance between all pairs across two sets of points; you can read about it in the [documentation](http://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.distance.cdist.html).

##Matplotlib

[Matplotlib](http://matplotlib.org/) is a plotting library. In this section give a brief introduction to the `matplotlib.pyplot` module, which provides a plotting system similar to that of MATLAB.
"""

import matplotlib.pyplot as plt

"""By running this special iPython command, we will be displaying plots inline:"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline

"""###Plotting

The most important function in `matplotlib` is `plot`, which allows you to plot 2D data. Here is a simple example:

Compute the `x` and `y` coordinates for points on a sine curve
"""

x = np.arange(0, 3 * np.pi, 0.1)
y = np.sin(x)

"""Plot the points using matplotlib"""

plt.plot(x, y)

"""With just a little bit of extra work we can easily plot multiple lines at once, and add a title, legend, and axis labels:"""

y_sin = np.sin(x)
y_cos = np.cos(x)

"""Plot the points using `matplotlib`"""

plt.plot(x, y_sin)
plt.plot(x, y_cos)
plt.xlabel('x axis label')
plt.ylabel('y axis label')
plt.title('Sine and Cosine')
plt.legend(['Sine', 'Cosine'])

"""You can read much more about the `plot` function in the [documentation](http://matplotlib.org/api/pyplot_api.html#matplotlib.pyplot.plot).

###Subplots

You can plot different things in the same figure using the subplot function. Here is an example:

Compute the `x` and `y` coordinates for points on sine and cosine curves
"""

x = np.arange(0, 3 * np.pi, 0.1)
y_sin = np.sin(x)
y_cos = np.cos(x)

"""- Set up a subplot grid that has height 2 and width 1, and set the first such subplot as active

- Make the first plot

- Set the second subplot as active, and make the second plot

- Show the figure
"""

plt.subplot(2, 1, 1)

plt.plot(x, y_sin)
plt.title('Sine')

plt.subplot(2, 1, 2)
plt.plot(x, y_cos)
plt.title('Cosine')

plt.show()

"""You can read much more about the `subplot` function in the [documentation](http://matplotlib.org/api/pyplot_api.html#matplotlib.pyplot.subplot).

###Images

You can use the `imshow` function to show images. Here is an example:
"""

import numpy as np
from scipy.misc import imread, imresize
import matplotlib.pyplot as plt

img = imread('assets/cat.jpg')
img_tinted = img * [1, 0.95, 0.9]

"""- Show the original image

- Show the tinted image

- A slight gotcha with imshow is that it might give strange results if presented with data that is not `uint8`
    + To work around this, we explicitly cast the image to `uint8` before displaying it
"""

plt.subplot(1, 2, 1)
plt.imshow(img)

plt.subplot(1, 2, 2)

plt.imshow(np.uint8(img_tinted))
plt.show()